import { readFileSync } from "node:fs";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

function makeTranslator(hostname) {
  const dictJs = readFileSync(join(root, "build/chrome/dictionary.js"), "utf8");
  const trJs = readFileSync(join(root, "build/chrome/translations.js"), "utf8");
  const ctx = { self: { location: { hostname } }, console };
  vm.createContext(ctx);
  vm.runInContext(dictJs.replace(/typeof self !== "undefined"/g, "true"), ctx);
  vm.runInContext(
    trJs
      .replace(/typeof self !== "undefined"/g, "true")
      .replace(/location\.hostname/g, "self.location.hostname"),
    ctx
  );
  return ctx.self.WickJpTranslations;
}

const observed = {
  "wickbot.com": [
    "New Dashboard",
    "Old Dashboard",
    "Diamond",
    "Discord moderation and security that is always one step ahead",
    "Invite",
    "Dashboard",
    "Servers",
    "Raids Stopped",
    "Nukes Stopped",
    "A new version of Wick released!",
    "Discord Server",
    "Documentation",
    "Support",
    "Premium",
    "Home",
    "Iron out your Discord server and fully secure it. Go Premium.",
    "plans",
    "more",
    "Discord's largest communities use Premium",
    "Members",
    "Premium Servers",
    "Total Members",
    "Raids Stopped",
    "Nuke Attempts",
    "Banned Accounts",
    "Kicked Accounts",
    "Quarantined Accounts",
    "go back",
    "per month",
    "Advanced Anti Raid",
    "Advanced Anti Nuke",
    "Advanced Automod",
    "Advanced Quarantine",
    "Smart Backups",
    "Advanced Lockdown System",
    "Customizable Verification",
    "Increased Ratelimits",
    "subscribe",
    "VIP",
    "Everything from Premium",
    "Dedicated Resources",
    "Custom Branding",
    "Super Low Latency",
    "12 Premium Servers",
    "Join Raid",
    "All raids blocked without you worrying.",
    "Advanced Anti Nuke",
    "Your server is monitored 24/7 for any suspicious activity.",
    "Backups",
    "Backups of your server taken automatically, load and synchronize them easily\n\t\t\t\t\t\t\t\t\t\t\twith your server.",
    "Advanced Automod",
    "Several additional filters and a system that handles mass spam efficiently",
    "AND MORE",
    "A lot of new solid moderation and features waiting for you to discover."
  ],
  "dashboard.wickbot.com": [
    "Servers",
    "Subscriptions",
    "Review",
    "Referrals",
    "Logout",
    "Select the server you want to manage",
    "Filter:",
    "Lost control over Wick in a server?",
    "Overview",
    "Details",
    "Server Name",
    "Server ID",
    "Shard ID",
    "Type",
    "standard",
    "Members",
    "Security",
    "Notes",
    "Wick lacks the Administrator permission. You are allowing critical bypasses and nukes.",
    "Wick can't monitor 3 roles. Anyone with these roles is 100% immune and safe from Wick.",
    "You have 7 roles that can natively Kick/Ban. You should remove the native moderation permissions from these roles and force your staff to instead use Wick's moderation commands that are supervised by Wick's anti nuke:",
    "Recent Activity",
    "Quick Systems Overview",
    "Auto Mod",
    "Anti Spam, Anti Advertising, Anti Phishing and all the message filters.",
    "Settings",
    "Anti Nuke",
    "The system that monitors your staff members and guards your server away from getting nuked.",
    "Join Gate",
    "All of the instant filters that scan new members and bots joining your server.",
    "Join Raid",
    "The advanced system that monitors your server joins and reacts if a raid is targeting your server.",
    "premium",
    "Verification",
    "Wick's infamous verification gate that your new members need to pass in order to get access to your server.",
    "refresh server",
    "Wizard",
    "Miscellaneous",
    "Permits",
    "Logging",
    "new",
    "Backups",
    "Lockdown",
    "Appeals",
    "General",
    "Filters",
    "Discord",
    "Whitelist",
    "Panic Mode",
    "Server Joins",
    "Automod",
    "General Settings",
    "Status",
    "AutoMod Status",
    "Use the automod module.",
    "Use the anti spam.",
    "Monitor unwhitelisted webhooks.",
    "AutoMod Mode",
    "You needed more info?",
    "Here is more info you wanted. You're welcome!",
    "Heat System",
    "Auto Timeouts",
    "Use the auto timeouts.",
    "Regular Strike Duration",
    "minute",
    "CAP Strike Duration",
    "s",
    "Multiply timeouts.",
    "Enable Multiplier",
    "Multiplier Percentage",
    "Heat Settings",
    "Max Heat",
    "The member's heat starts accumulating until it reaches",
    "where the Automod will trigger, and the filter that generated the most heat is picked as the reason behind the trigger. This chosen filter's action will be used too.",
    "Heat Degradation (every second)",
    "While time is passing, the heat accumulated by the member drops gradually every single second by",
    "Heat reset",
    "Once the member triggers Wick's automod, the member's heat will be reset down to",
    "Set current heat to 0% after punishment.",
    "AUTO LOCKDOWN",
    "Auto Lockdown Status",
    "Use the auto lockdown module.",
    "Mentions Lockdown",
    "Mentions Trigger Status",
    "Use the mentions auto lockdown trigger.",
    "Trigger Count",
    "Have Wick react when at least",
    "mentions",
    "from non whitelisted members have been made in the past",
    "3 seconds",
    "Mentions",
    "Trigger Count History",
    "from non whitelisted members have\n\t\t\t\t\t\t\t\t\t\t\t\t\tbeen made in the past",
    "second",
    "Strikes Lockdown",
    "SOON",
    "JoinRaid Lockdown",
    "Anti Nuke Status",
    "Use the antinuke module.",
    "Detect and react to member prunes.",
    "Have Wick guard your server's vanity url.",
    "Auto Quarantine",
    "Use the auto quarantine module.",
    "Strict Mode",
    "Punish unauthorized admins giving dangerous perms to any role in the\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tserver.",
    "Strict Member Role Addition",
    "Punish unauthorized admins giving dangerous perms to other members.",
    "Monitor Public Roles",
    "Protect",
    "and main roles from getting dangerous permissions.",
    "Monitor Channel Permissions",
    "and main roles from getting dangerous CHANNEL permissions.",
    "Quarantine Whitelist",
    "This whitelist allows users to touch members that are in Quarantine,\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tit doesn't mean that the whitelisted users won't be quarantined for\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tanything, just when it comes to editing the roles of a Quarantine\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmember",
    "Join gate",
    "Join Gate Status",
    "Use the joingate module.",
    "DM members when punished.",
    "Bot Additions",
    "Target bots added by unauthorized members.",
    "Trigger Action",
    "Trigger Action represents what Wick does once this filter triggers.",
    "kick",
    "is Discord's native kick feature",
    "Kick",
    "Unverified Bot Additions",
    "Target Discord Unverified bots added by any.",
    "Since you have the bot addition filter enabled, you technically could disable this filter if you want authorized members to add any type of bots.",
    "No Avatar",
    "Target accounts that have no profile pictures.",
    "Suspicious Account",
    "Target accounts Wick deems suspicious.",
    "Advertising Name",
    "Target accounts with invite links in usernames.",
    "mute",
    "is Discord's native timeout feature used to prevent the",
    "member",
    "from sending messages or joining voice channels",
    "Timeout",
    "Account Age",
    "Target accounts younger than a specified timeframe.",
    "Minimum Account Age",
    "day",
    "Username",
    "Target accounts that have a username that match your list.",
    "Enable this filter POST join too.",
    "This filter works when the member",
    "JOINS",
    "the server, enable this field to\n\t\t\t\t\t\t\t\t\t\t\thave it run anytime the member changes the username/nickname, this is useful for\n\t\t\t\t\t\t\t\t\t\t\traid accounts that try to bypass the filter with a different name, then change\n\t\t\t\t\t\t\t\t\t\t\tback to the intended name.",
    "ban",
    "is Discord's native ban feature plus the bulk deletion of the",
    "'s messages that were sent the entire week",
    "Ban",
    "Strict Words",
    "Add Word",
    "Wildcard Words",
    "The username must exactly match one of the elements below, Case\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tinsensitive. If you have the word \"Discord\" added, the full username of\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tthe account joining must be \"discord\".",
    "Note: Wick sanitizes the username and simplifies it before matching.",
    "The username needs to INCLUDE one of the elements below, Case\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tinsensitive. If you have the word \"nitro\" added, a user with the name\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"discordnitro\" will be targeted.",
    "Verification Status",
    "Use the verification module.",
    "Quarantine user on join (Not recommended)",
    "This makes Wick add new members to Quarantine once they join, this is a legacy setting and should not be toggled.",
    "Set autoroles instead of adding them.",
    "Have Wick",
    "enforce",
    "the main roles instead of adding them to the member's existing list of roles, meaning after the user successfully verifies, Wick will replace ALL of their roles with your main roles, other roles will be removed.",
    "Disable this if you have payment/patreon roles or harmless accessory roles that are given on join.",
    "Verification Targets",
    "Do you want Wick to force",
    "EVERYONE",
    "or",
    "those Wick deems",
    "sus to go through Wick's verification?",
    "If you choose",
    "Suspicious",
    ", non-suspicious users will be automatically given the autoroles.",
    "Everyone",
    "Fail Action",
    "If the action is set to",
    "Keep Unverified",
    ", the member will always remain in your server unverified until they go over Wick's verification process.",
    "Kick",
    "Ban",
    ", Wick will start counting the verification duration set below",
    "2 minutes",
    "from the moment they join your server, if they fail to verify via Wick during this duration, they will be punished.",
    "Verification Mode",
    "What kind of verification method do you want?",
    "Website",
    ", users will be redirected to Wick's verification website where they can verify seamlessly.",
    "Channel",
    ", users will verify seamlessly in the same verification channel without going anywhere else.",
    "DMs",
    ", users will be pass verification in DMs (Not Recommended).",
    "Rucaptcha",
    ", your users will be given the Rucaptcha in the same channel (HEAVILY Not Recommended).",
    "Instant Access",
    ", your users will be verified once they click the",
    "Verify",
    "button, no verification or anything, access through a button put simply.",
    "Wick Captcha (Channel)",
    "Display helpful notes alongside the captcha.",
    "Verification Duration",
    "If you have your",
    "set to",
    ", this duration starts when the member",
    "clicks",
    "the",
    "button, Wick tells them they failed to verify once this duration ends and they remain in the server.",
    "joins",
    "the server, Wick will kick/ban them once this duration ends.",
    "Verification Channel",
    "This is where your users will be able to verify through Wick, it's recommended to have Wick set this channel up (based on your settings)",
    "Select Channel",
    "Wick Captcha",
    "Captcha Height",
    "Pixels",
    "Captcha Width",
    "Font Size",
    "Font Color",
    "Captcha Answer",
    "Characters",
    "AZ",
    "Decoys",
    "Show a colored trace that follows the captcha characters.",
    "Add a mixed character under each captcha character.",
    "Show small spread-around characters to trick scripts.",
    "Decoy Color",
    "Prefix",
    "command",
    "Use slash commands.",
    "Minify Wick's message replies to compact embeds.",
    "Delete Wick's auto messages after few seconds.",
    "Always enforce the proper permissions of Quarantine role in channels.",
    "Always ignore commands issued by members without any permits.",
    "STATICS",
    "LOGS CHANNEL",
    "This is where Wick logs every single action it makes, this is your go-to\n\t\t\t\t\t\t\t\t\t\t\t\t\t\twhen you want to check more details about Wick has done.",
    "MODLOGS CHANNEL",
    "This is where the moderation actions made by your staff members using\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tWick's moderation commands are logged.",
    "QUARANTINE ROLE",
    "This role is super important to Wick, it's the role used for any\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tQuarantine action, and also the action used to isolate rogue accounts",
    "Quarantine",
    "MAIN ROLES",
    "Main Roles are the roles you usually give to ALL your members, they are\n\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsidered by all of Wick's systems including the verification. An\n\t\t\t\t\t\t\t\t\t\t\t\t\t\texample of a main role would be the common @Members or @Verified roles",
    "Moderation Commands",
    "Display a confirmation message before executing the moderation action\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ta moderator wants.",
    "Always DM the members punished regardless of the presence of a",
    "?dm",
    "parameter",
    "Always delete the moderation execution messages for regular prefix\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcommands.",
    "Hide the staff member responsible when DMing the punished member.",
    "Default Timeout Duration",
    "You want",
    "28 days",
    "to be the default timeout duration if no custom duration was provided when\n\t\t\t\t\t\t\t\t\t\t\t\t\t\ttiming out member(s)",
    "Days Purged on Bans",
    "When using the ban command, Wick should also purge",
    "days worth of messages related to the banned member(s).",
    "Days",
    "Auto Moderation",
    "Display the reason behind the auto punishment in the message Wick\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsends.",
    "Always purge the messages sent by the punished member found in the\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\trecent 100 messages.",
    "Consider only owners, trusted admins and any member with the flags (IMMUNITY|AUTOMOD IMMUNITY) to be considered staff members. Punish\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tanyone else triggering the auto mod.",
    "Auto Warn Actions",
    "Issue an action once a member reaches certain points.",
    "Base Points",
    "When a moderator warns a certain member,",
    "points are added to the member's record. If the member\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treaches a point that represents an action in the section below, then\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tthe member is punished.",
    "Points",
    "Custom Actions",
    "No Custom Actions",
    "Permits",
    "Customize your permissions.",
    "Name",
    "Actions",
    "Extra Owner",
    "OWNER",
    "IMMUNITY",
    "Trusted Admin",
    "Admins",
    "Moderators",
    "Custom Logging",
    "wick",
    "discord",
    "Wick Logs",
    "All of Wick logs that don't have any channel to go to will be sent here.",
    "Mod Logs",
    "The moderation actions done by your staff members using Wick will go here as cases.",
    "essential",
    "customize",
    "There are no customizable log channels set, add your own.",
    "Manage your lockdown modes",
    "manage",
    "settings",
    "2 issues",
    "Server Channels",
    "Server Roles",
    "Kick New Members",
    "Ban New Members",
    "APPEALS",
    "list",
    "blacklist",
    "ban",
    "timeout",
    "No pending appeals..",
    "WIZARD",
    "Start Wizard",
    "Setup Process",
    "This wizard helps simplify Wick's setup for you in detailed explained steps\n\t\t\t\t\t\t\t\t\t\t\t\tthat you can follow to ensure the proper behavior you want from Wick.",
    "Steps",
    "Auto Setup",
    "Antinuke",
    "Rescue Key",
    "You can choose a certain step if you want.",
    "The full setup could take around 3 minutes of your time.",
    "Subscription",
    "No active subscriptions found!",
    "Wick was unable to find any active running subscriptions linked to you.",
    "Plans",
    "select",
    "SOLD OUT"
  ]
};

const NUMERIC = /^[0-9.,$%kKmM\s]+$/;
const PUNCT_ONLY = /^[\s.,;:!?'"@#$%^&*()\-=+/\\|\[\]{}<>]+$/;
function isContent(s) {
  if (!s) return false;
  const t = s.trim();
  if (!t) return false;
  if (NUMERIC.test(t)) return false;
  if (PUNCT_ONLY.test(t)) return false;
  if (!/[A-Za-z]/.test(t)) return false;
  return true;
}

for (const [host, strings] of Object.entries(observed)) {
  const T = makeTranslator(host);
  const untranslated = [];
  const translated = [];
  for (const s of strings) {
    const res = T.translate(s);
    if (res === s) {
      if (isContent(s)) untranslated.push(s);
    } else {
      translated.push([s, res]);
    }
  }
  console.log("==", host, "==");
  console.log("translated:", translated.length, "untranslated:", untranslated.length);
  for (const u of untranslated) console.log("  MISS:", JSON.stringify(u));
}
