import { readFileSync, readdirSync, writeFileSync, mkdirSync, rmSync, cpSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const srcDir = join(root, "src");
const translationsDir = join(srcDir, "translations");
const buildDir = join(root, "build");

const KNOWN_DOMAINS = ["wickbot.com", "www.wickbot.com", "dashboard.wickbot.com"];

function loadJson(file) {
  return JSON.parse(readFileSync(file, "utf8"));
}

function normalizeKey(s) {
  return s.replace(/\s+/g, " ").trim();
}

function newScope() {
  return { entries: {}, multiline: [], titles: { exact: {}, suffix: {} } };
}

function mergeInto(target, data, sourceFile) {
  if (data.entries) {
    for (const [k, v] of Object.entries(data.entries)) {
      const key = normalizeKey(k);
      if (target.entries[key] && target.entries[key] !== v) {
        console.warn(`[wick-jp] conflict in same scope: "${key}" "${target.entries[key]}" -> "${v}" (in ${sourceFile})`);
      }
      target.entries[key] = v;
    }
  }
  if (data.multiline) {
    for (const m of data.multiline) {
      target.multiline.push({ key: normalizeKey(m.lines.join(" ")), ja: m.ja });
    }
  }
  if (data.titles) Object.assign(target.titles.exact, data.titles);
}

function buildPerDomainDictionaries() {
  const byDomain = {};
  for (const d of KNOWN_DOMAINS) byDomain[d] = newScope();
  let templates = [];
  let titlePatterns = { exact: {}, suffix: {} };
  const glossary = newScope();

  for (const file of readdirSync(translationsDir).sort()) {
    if (!file.endsWith(".json")) continue;
    const data = loadJson(join(translationsDir, file));

    if (file === "title-patterns.json") {
      Object.assign(titlePatterns.exact, data.exact || {});
      Object.assign(titlePatterns.suffix, data.suffix || {});
      continue;
    }
    if (file === "templates.json") {
      templates = data.patterns || [];
      continue;
    }
    if (file === "glossary.json") {
      mergeInto(glossary, data, file);
      continue;
    }

    const scope = Array.isArray(data.scope) && data.scope.length > 0 ? data.scope : KNOWN_DOMAINS;
    for (const domain of scope) {
      if (!byDomain[domain]) byDomain[domain] = newScope();
      mergeInto(byDomain[domain], data, file);
    }
  }

  for (const d of Object.keys(byDomain)) {
    const target = byDomain[d];
    for (const [k, v] of Object.entries(glossary.entries)) {
      if (!(k in target.entries)) target.entries[k] = v;
    }
    Object.assign(target.titles.exact, titlePatterns.exact);
    Object.assign(target.titles.suffix, titlePatterns.suffix);
  }

  return { byDomain, templates };
}

function emitDictionary({ byDomain, templates }) {
  const banner = "/* AUTO GENERATED by scripts/build.mjs - do not edit. */\n";
  const body = `(function(){
const BY_DOMAIN = ${JSON.stringify(byDomain, null, 2)};
const TEMPLATES = ${JSON.stringify(templates, null, 2)};
if (typeof self !== "undefined") {
  self.__WICK_JP_DICT_BY_DOMAIN__ = BY_DOMAIN;
  self.__WICK_JP_TEMPLATES__ = TEMPLATES;
}
})();
`;
  return banner + body;
}

function copyShared(targetDir) {
  for (const name of ["translations.js", "content.js", "popup.html", "popup.js"]) {
    cpSync(join(srcDir, name), join(targetDir, name));
  }
  cpSync(join(srcDir, "_locales"), join(targetDir, "_locales"), { recursive: true });
  if (existsSync(join(srcDir, "icons"))) {
    cpSync(join(srcDir, "icons"), join(targetDir, "icons"), { recursive: true });
  } else {
    mkdirSync(join(targetDir, "icons"), { recursive: true });
  }
}

function emitBrowser(target, dictBundle) {
  const targetDir = join(buildDir, target);
  rmSync(targetDir, { recursive: true, force: true });
  mkdirSync(targetDir, { recursive: true });
  const manifestFile = target === "firefox" ? "manifest.firefox.json" : "manifest.chrome.json";
  const manifest = loadJson(join(srcDir, manifestFile));
  manifest.content_scripts[0].js = ["dictionary.js", ...manifest.content_scripts[0].js];
  writeFileSync(join(targetDir, "manifest.json"), JSON.stringify(manifest, null, 2));
  copyShared(targetDir);
  writeFileSync(join(targetDir, "dictionary.js"), emitDictionary(dictBundle));
  const sizes = Object.entries(dictBundle.byDomain)
    .map(([d, s]) => `${d}: ${Object.keys(s.entries).length} entries / ${s.multiline.length} multiline`)
    .join("; ");
  console.log(`[wick-jp] built ${target} → ${sizes}; templates=${dictBundle.templates.length}`);
}

const dictBundle = buildPerDomainDictionaries();
emitBrowser("chrome", dictBundle);
emitBrowser("firefox", dictBundle);
